import { usuariosDocRef, getDoc, setDoc, updateDoc } from '../config/firebaseConfig.js';

export async function subirAlumnos() {
    const alumnos = [
        { NOMBRE: "ANALY JUANITA ALCAZAR HERMOZA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "HELVIDIA CATHERINE CASTILLO JIMÉNEZ", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "MARITZA CORONEL BENAVIDES", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "VILMA CORONEL BENAVIDES", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "CARMEN VERÓNICA DAZA SANTA MARTA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "ENRIQUE ERNESTO DEL ÁGUILA CASTAÑEDA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "JUAN CARLOS DEL ÁGUILA CASTAÑEDA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "JULIO CÉSAR DEL ÁGUILA QUINTANA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "GINO ALEJANDRO DEZA LA CUNZA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "DINA ELENA DÍAZ AGUILAR", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "RICARDO DÍAZ BARDALEZ", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "EVELYN RUTH DÍAZ CAMPOS", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "GOMER DÍAZ DÍAZ", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "RUDBY DÍAZ OCMIN", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "DANTE DAVID DÍAZ PUERTA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "DENNISE ERIKA DÍAZ RODRÍGUEZ", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "NOÉ LEVI DIAZ SAGASTEGUI", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "NORBIL DIAZ SAGASTEGUI", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "ROITER EGOAVIL FLORES", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "LLINA CECILIA ELORRIAGA OJANAMA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "EMELINA ESPINAL IDROGO", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "KHATRYN ESTHELA FASANANDO HERNÁNDEZ", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "DEYSI FLORES TELLO", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "ALBERTO EINSTEN FRANCO CASIQUE", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "YOY MARINA FRANCO ESTRELLA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "NATHAN FRÍAS GOMEZ", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "GINNY ASTRID GARCÍA AMPUERO", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "GLENN ALAIN GARCÍA AMPUERO", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "CHRISTIAN JOSUÉ GARCÍA AZCARATE", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "DÉLFIDO GARCÍA MACEDO", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "ALAN GARCÍA QUIROZ", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "ALAN NILS GARCÍA SOPLIN", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "LUIS ALBERTO GARCÍA TICLIAHUANCA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "KATERYNE GARCÍA VILLANUEVA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "MARÍA LUISA GÓNGORA REÁTEGUI", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "CARLOS MIGUEL GONZALES RUIZ", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "ISABEL GUADALUPE ARMAS", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "FERNANDO GUEVARA FUENTES", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "DIANA KARIN HERRERA MEDINA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "ROSALINA HOYOS DÍAZ", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "ELVI HUAMÁN CUBAS", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "LUIS ENRIQUE HUAMÁN GUTIÉRREZ", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "CLAUDIA DE LOS MILAGROS MORENO ELERA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "CARLOS ALBERTO PÉREZ BARRERA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "KLAUSS ANTONY REÁTEGUI PEREYRA", URL01: "", URL02: "", VOTO: "" },
        { NOMBRE: "DILMER TORRES BARBOZA", URL01: "", URL02: "", VOTO: "" }
    ];

    await updateDoc(usuariosDocRef, { usuarios: alumnos });
}